# Generated by Django 4.2.5 on 2023-09-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TritoneSpotifyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('year_released', models.CharField(max_length=255)),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
