# Generated by Django 4.2.5 on 2023-09-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tritones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tritonespotifytrack',
            old_name='year_released',
            new_name='release_year',
        ),
        migrations.AddField(
            model_name='tritonespotifytrack',
            name='image_url',
            field=models.CharField(default='https://open.spotify.com/track/046sxR47LTPEZG8j0il8M8?si=b73937ff8aa944c7', max_length=255),
            preserve_default=False,
        ),
    ]
